 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace ServerPIDL
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RegisterRequest = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID RegisterResponse = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID LoginRequest = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID LoginResponse = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID CreatePlayer = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID GetPlayerRequest = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID GetPlayerResponse = (Nettention.Proud.RmiID)2000+7;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RegisterRequest,
			RegisterResponse,
			LoginRequest,
			LoginResponse,
			CreatePlayer,
			GetPlayerRequest,
			GetPlayerResponse,
		};
	}
}

				 
