 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace SendText
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Send = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID Login = (Nettention.Proud.RmiID)2000+2;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Send,
			Login,
		};
	}
}

				 
